const STREAM_BEGIN = 0;
const STREAM_EOF = 1;
const STREAM_DRY = 2;
const SET_BUFFER_LENGTH = 3;
const STREAM_IS_RECORDED = 4;
const PING_REQUEST = 6;
const PING_RESPONSE = 7;

module.exports = {
	STREAM_BEGIN,
	STREAM_EOF,
	STREAM_DRY,
	SET_BUFFER_LENGTH,
	STREAM_IS_RECORDED,
	PING_REQUEST,
	PING_RESPONSE,
};
