const SET_CHUNK_SIZE = 1;
const ABORT_MESSAGE = 2;
const ACKNOWLEDGEMENT = 3;
const USER_CONTROL_MESSAGE = 4;
const WINDOW_ACKNOWLEDGEMENT_SIZE = 5;
const SET_PEER_BANDWIDTH = 6;
const AUDIO_MESSAGE = 8;
const VIDEO_MESSAGE = 9;
const DATA_MESSAGE_AMF3 = 15;
const SHARED_OBJECT_MESSAGE_AMF3 = 16;
const COMMAND_MESSAGE_AMF3 = 17;
const DATA_MESSAGE_AMF0 = 18;
const SHARED_OBJECT_MESSAGE_AMF0 = 19;
const COMMAND_MESSAGE_AMF0 = 20;
const AGGREGATE_MESSAGE = 22;

module.exports = {
	SET_CHUNK_SIZE,
	ABORT_MESSAGE,
	ACKNOWLEDGEMENT,
	USER_CONTROL_MESSAGE,
	WINDOW_ACKNOWLEDGEMENT_SIZE,
	SET_PEER_BANDWIDTH,
	AUDIO_MESSAGE,
	VIDEO_MESSAGE,
	DATA_MESSAGE_AMF3,
	SHARED_OBJECT_MESSAGE_AMF3,
	COMMAND_MESSAGE_AMF3,
	DATA_MESSAGE_AMF0,
	SHARED_OBJECT_MESSAGE_AMF0,
	COMMAND_MESSAGE_AMF0,
	AGGREGATE_MESSAGE,
};
