const USE = 1;
const RELEASE = 2;
const REQUEST_CHANGE = 3;
const CHANGE = 4;
const SUCCESS = 5;
const SEND_MESSAGE = 6;
const STATUS = 7;
const CLEAR = 8;
const REMOVE = 9;
const REQUEST_REMOVE = 10;
const USE_SUCCESS = 11;
const UNKNOWN = 12;
const CHANGE_ECHO = 13;
const REQUEST_CLEAR = 14;

module.exports = {
	USE,
	RELEASE,
	REQUEST_CHANGE,
	CHANGE,
	SUCCESS,
	SEND_MESSAGE,
	STATUS,
	CLEAR,
	REMOVE,
	REQUEST_REMOVE,
	USE_SUCCESS,
	UNKNOWN,
	CHANGE_ECHO,
	REQUEST_CLEAR,
};
